ConfigurationManager.Web/Models/ErrorViewModel.cs
using System;

namespace ConfigurationManager.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ConfigurationManager.Web/Controllers/ConfigurationManagementController.cs
using Microsoft.AspNetCore.Mvc;
using Shared.Interfaces;
using System.Collections.Generic;
using System.Threading.Tasks;
using Shared.Models;
using System.Linq;
using System;
using Shared.Enums;

namespace ConfigurationManager.Web.Controllers
{
    public class ConfigurationManagementController : Controller
    {
        private readonly IConfigurationRepository _configurationRepository;

        public ConfigurationManagementController(IConfigurationRepository configurationRepository)
        {
            _configurationRepository = configurationRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GetConfigurations()
        {
            var draw = HttpContext.Request.Form["draw"].FirstOrDefault();
            var start = HttpContext.Request.Form["start"].FirstOrDefault();
            var length = HttpContext.Request.Form["length"].FirstOrDefault();
            var sortColumn = HttpContext.Request.Form["columns[" + HttpContext.Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
            var sortColumnDirection = HttpContext.Request.Form["order[0][dir]"].FirstOrDefault();
            var searchValue = HttpContext.Request.Form["search[value]"].FirstOrDefault();

            // Pagination
            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;

            // Total document count
            var recordsTotal = await _configurationRepository.GetCountAsync(searchText: searchValue);

            var data = await _configurationRepository.GetAllConfigurationItemsWithPaginationAsync(pageSize, skip, searchText: searchValue);

            return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });
        }

        [HttpPost]
        public async Task<IActionResult> CreateConfiguration(ConfigurationItem configurationItem)
        {
            try
            {
                configurationItem.Type = ((ConfigurationTypes)Convert.ToInt32(configurationItem.Type)).ToString();

                await _configurationRepository.InsertConfigItemAsync(configurationItem);

                return Json(new { success = true, message = "Konfigürasyon başarılı bir şekilde eklendi." });
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return Json(new { success = false, message = "Konfigürasyon oluşturulurken bir hata oluştu!" });
        }

        [HttpPost]
        public async Task<IActionResult> UpdateConfiguration(ConfigurationItem configurationItem)
        {
            try
            {
                configurationItem.Type = ((ConfigurationTypes)Convert.ToInt32(configurationItem.Type)).ToString();

                var response = await _configurationRepository.UpdateConfigItemAsync(configurationItem);

                if (response)
                {
                    return Json(new { success = true, message = "Konfigürasyon başarılı bir şekilde güncellendi." });
                }

                return Json(new { success = false, message = "Konfigürasyon güncellenirken bir hata oluştu!" });
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return Json(new { success = false, message = "Konfigürasyon güncellenirken bir hata oluştu!" });
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfiguration(string id)
        {
            try
            {
                var response = await _configurationRepository.DeleteConfigItemAsync(id);

                if (response)
                {
                    return Json(new { success = true, message = "Konfigürasyon başarılı bir şekilde silindi." });
                }

                return Json(new { success = false, message = "Konfigürasyon silinirken bir hata oluştu!" });
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return Json(new { success = false, message = "Konfigürasyon silinirken bir hata oluştu!" });
        }
    }
}

ConfigurationManager.Web/Controllers/HomeController.cs
using ConfigurationManager.Web.Models;
using ConfigurationReaderLib;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Shared.Interfaces;
using Shared.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ConfigurationManager.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IConfigurationRepository _configurationRepository;

        public HomeController(ILogger<HomeController> logger, IConfigurationRepository configurationRepository)
        {
            _logger = logger;
            _configurationRepository = configurationRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ConfigurationManager.Web/Views/ConfigurationManagement/Index.cshtml
@using Shared.Enums;

<h1>Configuration List</h1>
<button class="btn btn-sm btn-success" data-toggle="modal" data-target="#createConfigurationModal">Create New Configuration</button>

<table id="configurationTable" class="display">
    <thead>
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Value</th>
            <th>IsActive</th>
            <th>ApplicationName</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

<!-- Create Configuration Modal -->
<div class="modal fade" id="createConfigurationModal" tabindex="-1" aria-labelledby="createConfigurationModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createConfigurationModalLabel">Create New Configuration</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="createConfigurationForm">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" class="form-control" id="Name" required>
                    </div>
                    <div class="form-group">
                        <label for="Type">Type</label>
                        <select class="form-select" asp-items="Html.GetEnumSelectList<ConfigurationTypes>()" id="Type" required>
                            <option selected>Select A Type</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="Value">Value</label>
                        <input type="text" class="form-control" id="Value" required>
                    </div>
                    <div class="form-group">
                        <label for="IsActive">IsActive</label>
                        <input type="checkbox" class="form-control" id="IsActive">
                    </div>
                    <div class="form-group">
                        <label for="ApplicationName">ApplicationName</label>
                        <input type="text" class="form-control" id="ApplicationName" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Create</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Update Configuration Modal -->
<div class="modal fade" id="updateConfigurationModal" tabindex="-1" aria-labelledby="updateConfigurationModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="updateConfigurationModalLabel">Update Configuration</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="updateConfigurationForm">
                    <input type="hidden" id="updateId">
                    <div class="form-group">
                        <label for="updateName">Name</label>
                        <input type="text" class="form-control" id="updateName" required>
                    </div>
                    <div class="form-group">
                        <label for="updateType">Type</label>
                        <select class="form-select" asp-items="Html.GetEnumSelectList<ConfigurationTypes>()" id="updateType" required>
                            <option selected>Select A Type</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="updateValue">Value</label>
                        <input type="text" class="form-control" id="updateValue" required>
                    </div>
                    <div class="form-group">
                        <label for="updateIsActive">IsActive</label>
                        <input type="checkbox" class="form-control" id="updateIsActive">
                    </div>
                    <div class="form-group">
                        <label for="updateApplicationName">ApplicationName</label>
                        <input type="text" class="form-control" id="updateApplicationName" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Update</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    var table = $('#configurationTable').DataTable({
        "processing": true,
        "serverSide": true,
        "rowId": "id",
        "searching": true,
        "ajax": {
            "url": "ConfigurationManagement/GetConfigurations",
            "type": "POST",
            "datatype": "json"
        },
        "columns": [
            { "data": "name" },
            { "data": "type" },
            { "data": "value" },
            { "data": "isActive" },
            { "data": "applicationName" },
            {
                "data": "id",
                "render": function (data, type, row, meta) {
                    return `
                                <button class="btn btn-sm btn-primary" onclick="editConfiguration('${data}')">Edit</button>
                                <button class="btn btn-sm btn-danger" onclick="deleteConfiguration('${data}')">Delete</button>
                            `;
                },
                "orderable": false
            }
        ]
    });

    $('#createConfigurationForm').on('submit', function (e) {
        e.preventDefault();
        var configuration = {
            Name: $('#Name').val(),
            Type: $('#Type').val(),
            Value: $('#Value').val(),
            IsActive: $('#IsActive')[0].checked,
            ApplicationName: $('#ApplicationName').val()
        };

        $.ajax({
            url: '/ConfigurationManagement/CreateConfiguration',
            type: 'POST',
            dataType: 'json',
            data: configuration,
            traditional: true,
            success: function (response) {
                if (response.success) {
                    table.ajax.reload();
                    $('#createConfigurationModal').modal('hide');
                    $('#createConfigurationForm')[0].reset();
                } else {
                    alert(response.message);
                }
            }
        });
    });

    $('#updateConfigurationForm').on('submit', function (e) {
        e.preventDefault();
        var configuration = {
            Id: $('#updateId').val(),
            Name: $('#updateName').val(),
            Type: $('#updateType').val(),
            Value: $('#updateValue').val(),
            IsActive: $('#updateIsActive')[0].checked,
            ApplicationName: $('#updateApplicationName').val()
        };

        $.ajax({
            url: '/ConfigurationManagement/UpdateConfiguration',
            type: 'POST',
            dataType: 'json',
            data: configuration,
            traditional: true,
            success: function (response) {
                if (response.success) {
                    table.ajax.reload();
                    $('#updateConfigurationModal').modal('hide');
                    $('#updateConfigurationForm')[0].reset();
                } else {
                    alert(response.message);
                }
            }
        });
    });

    $(document).ready(function () {
        window.editConfiguration = function (id) {
            var configuration = table.row('#' + id).data();
            $('#updateId').val(configuration.id);
            $('#updateName').val(configuration.name);
            $("#updateType option").each(function () {
                if ($(this).text() === configuration.type) {
                    $(this).prop("selected", true);
                }
            });
            $('#updateValue').val(configuration.value);
            $('#updateIsActive').attr("checked", configuration.isActive);
            $('#updateApplicationName').val(configuration.applicationName);
            $('#updateConfigurationModal').modal('show');
        };

        window.deleteConfiguration = function (id) {
            if (confirm('Bu konfigürasyonu silmek istediğinize emin misiniz?')) {
                $.ajax({
                    url: '/ConfigurationManagement/DeleteConfiguration',
                    type: 'POST',
                    dataType: 'json',
                    data: { id: id },
                    traditional: true,
                    success: function (response) {
                        if (response.success) {
                            table.ajax.reload();
                        } else {
                            alert(response.message);
                        }
                    }
                });
            }
        };
    });

</script>

ConfigurationManager.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    Hello!<br>To manage configurations please click the button below.<br>
    <a class="btn btn-primary mt-4" asp-controller="ConfigurationManagement" asp-action="Index">Configuration Management</a>
</div>

ConfigurationManager.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ConfigurationManager.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
            integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
            crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.8/css/dataTables.dataTables.css" />

    <script src="https://cdn.datatables.net/2.0.8/js/dataTables.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-center align-items-center">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="ConfigurationManagement" asp-action="Index">Configurations</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>